image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  UI_REGISTRY_IMAGE: ebispot/gwas-deposition-ui
  UI_SERVICE_NAME: gwas-deposition-ui

npm-build:
  image: node:10.15.3
  stage: build
  script:
    - npm -v
    - node -v
    - rm -rf node_modules
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/*
  only:
    - test/ci_cd
