image: docker:latest
services:
  - docker:dind

stages:
  - build

cache:
  paths:
    - node_modules/

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  UI_REGISTRY_IMAGE: ebispot/gwas-deposition-ui
  UI_SERVICE_NAME: gwas-deposition-ui

npm-build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/*
  only:
    - test/ci_cd
