image: docker:latest
services:
  - docker:dind

stages:
  - build
  - docker
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CI_REGISTRY_IMAGE: ebispot/gwas-deposition-ui
  UI_SERVICE_NAME: gwas-deposition-ui

npm-build:
  image: node:10.15.3
  stage: build
  script:
    - npm -v
    - node -v
    - rm -rf node_modules
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - build/*
  only:
    - master

docker-build:
  stage: docker
  script:
    - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
    - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
    - docker build --force-rm=true -t $UI_SERVICE_NAME:latest .
    - docker tag $UI_SERVICE_NAME:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - master

docker-build-release:
  variables:
    GIT_STRATEGY: none
  stage: docker
  script:
    - echo "$DOCKER_HUB_PASSWORD" > dhpw.txt
    - docker login -u "${DOCKER_HUB_USER}" --password-stdin < dhpw.txt
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

docker-deploy-sandbox:
  image: dtzar/helm-kubectl:2.13.1
  stage: deploy
  script:
    - echo "Deploy to sandbox server"
    - mkdir -p /root/.kube
    - echo ${SANBOX_KUBECONF} | base64 -d > /root/.kube/config
    - helm init
    - helm delete --purge gwas-deposition-ui || true
    - helm install --name gwas-deposition-ui --set k8Namespace=default,image.repository=$CI_REGISTRY_IMAGE,image.tag=$CI_COMMIT_SHA ./k8chart/ --wait
  environment:
    name: sandbox
  only:
    - master
